export const topics = {
  cs: [
    'Odvaha',
    'Disciplína',
    'Zvědavost',
    'Trpělivost',
    'Štěstí',
    'Změna',
    'Domov',
    'Samota',
    'Chaos',
    'Klid',
    'Respekt',
    'Důvěra',
    'Selhání',
    'Úspěch',
    'Riziko',
    'Volba',
    'Paměť',
    'Nuda',
    'Radost',
    'Strach',
    'Návyk',
    'Hranice',
    'Směr',
    'Smysl',
    'Vytrvalost',
    'Vděčnost',
    'Nepohodlí',
    'Upřímnost',
    'Pověst',
    'Pozornost',
    'Tempo',
    'Volnost',
    'Stabilita',
    'Odpovědnost',
    'Lehkost',
    'Pochybnost',
    'Rozvaha',
    'Jistota',
    'Empatie',
    'Originalita',
    'Perspektiva',
    'Rozhodnost',
    'Nadhled',
    'Poctivost',
    'Rovnováha',
    'Rozptýlení',
    'Klíč',
    'Začátek',
    'Konec',
    'Důslednost',
    'Spánek',
    'Únava',
    'Čas',
    'Peníze',
    'Krása',
    'Pravda',
    'Lež',
    'Zvyk',
    'Naděje',
    'Smutek',
    'Hrdost',
    'Stud',
    'Závist',
    'Láska',
    'Vášeň',
    'Prohra',
    'Vítězství',
    'Boj',
    'Hra',
    'Sen',
    'Cíl',
    'Práce',
    'Volno',
    'Cesta',
    'Most',
    'Krok',
    'Skok',
    'Pád',
    'Zlom',
    'Síla',
    'Slabost',
    'Návrat',
    'Odchod',
    'Mlčení',
    'Improvizace',
    'Detail',
    'Pauza',
    'Charakter',
    'Drobnost',
    'Tajemství',
    'Talent',
    'Touha',
    'Klam',
    'Zájem',
    'Otázka',
    'Pravidla',
    'Rituál',
    'Vkus',
    'Zlozvyk',
    'Nadšení',
    'Trpělivý čas',
    'Nejlepší rada',
    'Vysněné místo',
    'Klíčová technologie',
    'Hodnota chyb',
    'První dojem',
    'Říkat ne',
    'Zhroucené plány',
    'Mladšímu já',
    'Síla ticha',
    'Sebepřekonání',
    'Nicnedělání',
    'Vysněná dovednost',
    'Kniha života',
    'Nezapomenutelný den',
    'Dětský hrdina',
    'Pravé přátelství',
    'Tajné pravidlo',
    'Podivné jídlo',
    'Malé kroky',
    'Vyzrálost',
    'Síla otázky',
    'Síla příběhu',
    'Síla pauzy',
    'Síla nesouhlasu',
    'Dobré vystoupení',
    'Zajímavá konverzace',
    'Dochvilnost',
    'Příjemné překvapení',
    'Imponující vlastnost',
    'Více odvahy',
    'Vnitřní síla',
    'Idealizace minulosti',
    'Načasování',
    'Beze slov',
    'Prokrastinace',
    'Dobrý odpočinek',
    'Malé vítězství',
    'Strach z úspěchu',
    'Správná cesta',
    'Online debata',
    'Vliv prostředí',
    'Zdravá ambice',
    'Dopis sobě',
    'Společenský tlak',
    'Přiznat chybu',
    'Pět minut',
    'Prázdná slova',
    'Smysl pro míru',
    'Dobrý vkus',
    'Nový standard',
    'Skutečný zájem',
    'Denní rituál',
    'Výmluvy',
    'Vést druhé',
    'Tón hlasu',
    'Slyšet častěji',
    'Nepohodlné pravdy',
    'Být připraven',
    'Rychlá odpověď',
    'Kvalitní život',
    'Volnější názor',
    'Až po ztrátě',
    'Test důvěry',
    'Být dospělý',
    'Změna tempa',
    'Sám se sebou',
    'Pevné rozhodnutí',
    'Méně komentářů',
    'Zdravé sebevědomí',
    'Humor v krizi',
    'Nedotknutelný čas',
    'Vliv okolí',
    'Daný slib',
    'Zjednodušit život',
    'Profesionalita',
    'Neobyčejný den',
    'Brát vážně',
    'Začít znovu',
    'Soustředění',
    'Smysluplná debata',
    'Dlouhodobá motivace',
    'Dar odmítnutí',
    'Hodnota času',
    'Dobré rozhodnutí',
    'Drobná odvaha',
    'Hodnota klidu',
    'Před nosem',
    'Vůně dětství',
    'Domácí výuka',
    'Skrytá superschopnost',
    'Dobrý den',
    'Lepší zítřek',
    'Pomalejší reakce',
    'Sen vs cíl',
    'Začít vs vydržet',
    'Sebevědomí vs arogance',
    'Talent vs práce',
    'Pohodlí vs štěstí',
    'Chytrost vs laskavost',
    'Originalita vs spolehlivost',
    'Otázka vs odpověď',
    'Vliv vs moc',
    'Pohodlí vs výkon',
    'Autorita vs respekt',
    'Naděje vs očekávání',
    'Znalost vs moudrost',
    'Odvaha vs zbrklost',
    'Samota vs osamělost',
    'Co tě nakopne',
    'Co tě uklidní',
    'Co tě posunulo',
    'Když plán selže',
    'Když přijde tréma',
    'Když dojdou slova',
    'Kdy je dost',
    'První věta',
    'První pokus',
    'Poslední šance',
    'Pamětný omyl',
    'Tichá síla',
    'Příběh dne',
    'Drobná radost',
    'Komfortní zóna',
    'Pět minut ticha',
    'Knihy z dětství',
    'Cesta po vlastních',
    'Krok do neznáma',
    'Skok do vody',
    'Stojí za to',
    'Lekce z prohry',
    'Den bez plánu',
    'Tichá výhoda',
    'Hluboká voda',
    'Tužka',
    'Sešit',
    'Hrnek',
    'Konvice',
    'Lžíce',
    'Hřeben',
    'Zrcadlo',
    'Hodinky',
    'Peněženka',
    'Brýle',
    'Klobouk',
    'Boty',
    'Ručník',
    'Mýdlo',
    'Svíčka',
    'Polštář',
    'Lampa',
    'Židle',
    'Postel',
    'Dveře',
    'Okno',
    'Lednice',
    'Notebook',
    'Sluchátka',
    'Fotoaparát',
    'Telefon',
    'Klávesnice',
    'Kytara',
    'Klavír',
    'Šachy',
    'Karty',
    'Knihovna',
    'Pas',
    'Mince',
    'Bankovka',
    'Vizitka',
    'Auto',
    'Kolo',
    'Vlak',
    'Letadlo',
    'Loď',
    'Stan',
    'Strom',
    'List',
    'Kámen',
    'Mraky',
    'Déšť',
    'Sníh',
    'Hvězda',
    'Slunce',
  ],
  en: [
    'Courage',
    'Discipline',
    'Curiosity',
    'Patience',
    'Luck',
    'Change',
    'Home',
    'Solitude',
    'Chaos',
    'Calm',
    'Respect',
    'Trust',
    'Failure',
    'Success',
    'Risk',
    'Choice',
    'Memory',
    'Boredom',
    'Joy',
    'Fear',
    'Habit',
    'Boundaries',
    'Direction',
    'Meaning',
    'Persistence',
    'Gratitude',
    'Discomfort',
    'Honesty',
    'Reputation',
    'Attention',
    'Pace',
    'Freedom',
    'Stability',
    'Responsibility',
    'Lightness',
    'Doubt',
    'Thoughtfulness',
    'Certainty',
    'Empathy',
    'Originality',
    'Perspective',
    'Decisiveness',
    'Distance',
    'Integrity',
    'Balance',
    'Distraction',
    'Key',
    'Beginning',
    'Ending',
    'Consistency',
    'Sleep',
    'Fatigue',
    'Time',
    'Money',
    'Beauty',
    'Truth',
    'Lie',
    'Routine',
    'Hope',
    'Sadness',
    'Pride',
    'Shame',
    'Envy',
    'Love',
    'Passion',
    'Loss',
    'Victory',
    'Fight',
    'Play',
    'Dream',
    'Goal',
    'Work',
    'Leisure',
    'Journey',
    'Bridge',
    'Step',
    'Leap',
    'Fall',
    'Pivot',
    'Strength',
    'Weakness',
    'Return',
    'Departure',
    'Silence',
    'Improvisation',
    'Detail',
    'Pause',
    'Character',
    'Trifle',
    'Secret',
    'Talent',
    'Longing',
    'Illusion',
    'Interest',
    'Question',
    'Rules',
    'Ritual',
    'Taste',
    'Bad habit',
    'Enthusiasm',
    'Patient time',
    'Best advice',
    'Dream place',
    'Key technology',
    'Value of mistakes',
    'First impression',
    'Saying no',
    'Broken plans',
    'Younger self',
    'Power of silence',
    'Self-overcoming',
    'Doing nothing',
    'Dream skill',
    'Life-changing book',
    'Unforgettable day',
    'Childhood hero',
    'True friendship',
    'Secret rule',
    'Strangest meal',
    'Small steps',
    'Maturity',
    'A question\'s power',
    'A story\'s power',
    'Power of pause',
    'Power of disagreement',
    'A good speech',
    'Interesting conversation',
    'Punctuality',
    'Pleasant surprise',
    'Admirable trait',
    'More courage',
    'Inner strength',
    'Romanticized past',
    'Good timing',
    'Without words',
    'Procrastination',
    'Real rest',
    'Small win',
    'Fear of success',
    'The right path',
    'Online debate',
    'Power of place',
    'Healthy ambition',
    'Letter to self',
    'Social pressure',
    'Owning a mistake',
    'Five minutes',
    'Empty words',
    'Sense of measure',
    'Good taste',
    'A new standard',
    'Real interest',
    'Daily ritual',
    'Excuses',
    'Leading others',
    'Tone of voice',
    'Heard more often',
    'Uncomfortable truths',
    'Being prepared',
    'Quick answer',
    'A quality life',
    'Looser opinion',
    'Only after losing',
    'Trust test',
    'Being grown-up',
    'Change of pace',
    'Alone with self',
    'Firm decision',
    'Less commenting',
    'Healthy confidence',
    'Humor in crisis',
    'Untouchable time',
    'Influence of others',
    'A promise made',
    'Simplifying life',
    'Professionalism',
    'Extraordinary day',
    'Taking seriously',
    'Starting over',
    'Focus',
    'Meaningful debate',
    'Long-term drive',
    'Gift of refusal',
    'Value of time',
    'A good decision',
    'Small courage',
    'Value of calm',
    'Under your nose',
    'Childhood scent',
    'Home learning',
    'Hidden superpower',
    'A good day',
    'Better tomorrow',
    'Slower reaction',
    'Dream vs goal',
    'Starting vs sticking',
    'Confidence vs arrogance',
    'Talent vs work',
    'Comfort vs happiness',
    'Clever vs kind',
    'Original vs reliable',
    'Question vs answer',
    'Influence vs power',
    'Comfort vs performance',
    'Authority vs respect',
    'Hope vs expectation',
    'Knowledge vs wisdom',
    'Courage vs recklessness',
    'Solitude vs loneliness',
    'Your kick-off',
    'What calms you',
    'What moved you',
    'When plans fail',
    'Stage fright',
    'Wordless moments',
    'Enough is enough',
    'First sentence',
    'First attempt',
    'Last chance',
    'Memorable mistake',
    'Quiet strength',
    'Today\'s story',
    'A tiny joy',
    'Comfort zone',
    'Five quiet minutes',
    'Books from childhood',
    'Your own way',
    'Into the unknown',
    'Leap of faith',
    'Worth doing',
    'Lesson from losing',
    'Unplanned day',
    'Quiet advantage',
    'Deep water',
    'Pencil',
    'Notebook',
    'Mug',
    'Kettle',
    'Spoon',
    'Comb',
    'Mirror',
    'Wristwatch',
    'Wallet',
    'Glasses',
    'Hat',
    'Shoes',
    'Towel',
    'Soap',
    'Candle',
    'Pillow',
    'Lamp',
    'Chair',
    'Bed',
    'Door',
    'Window',
    'Fridge',
    'Laptop',
    'Headphones',
    'Camera',
    'Phone',
    'Keyboard',
    'Guitar',
    'Piano',
    'Chess',
    'Cards',
    'Bookshelf',
    'Passport',
    'Coin',
    'Banknote',
    'Business card',
    'Car',
    'Bike',
    'Train',
    'Airplane',
    'Ship',
    'Tent',
    'Tree',
    'Leaf',
    'Stone',
    'Clouds',
    'Rain',
    'Snow',
    'Star',
    'Sun',
  ],
};

export function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function sampleN(arr, n) {
  const copy = [...arr];
  const out = [];
  const count = Math.min(n, copy.length);
  for (let i = 0; i < count; i++) {
    const idx = Math.floor(Math.random() * copy.length);
    out.push(copy.splice(idx, 1)[0]);
  }
  return out;
}
